name: CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: hustcer/setup-nu@v3
        with:
          version: '0.80'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      - if: "matrix.os == 'macos-latest'"
        run: |
          nu -n -c "use action.nu *; test x86_64-apple-darwin"
      - if: "matrix.os == 'windows-latest'"
        run: |
          nu -n -c "use action.nu *; test x86_64-pc-windows-msvc"

  dist:
    needs:
      - test
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: hustcer/setup-nu@v3
        with:
          version: '0.80'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      - if: "matrix.os == 'macos-latest'"
        run: |
          nu -n -c "use action.nu *; dist aarch64-apple-darwin x86_64-apple-darwin"
      - if: "matrix.os == 'windows-latest'"
        run: |
          nu -n -c "use action.nu *; dist x86_64-pc-windows-msvc"
      - uses: actions/upload-artifact@v3
        with:
          path: |
            ipmb-js/*/release/ipmb_js.node
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ipmb-ffi/*.zip
            target/*.zip
            target/*.pdb

  publish:
    needs:
      - dist
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hustcer/setup-nu@v3
        with:
          version: '0.80'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3
      - run: |
          nu -n -c "use action.nu *; publish js"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
