name: dist js

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: hustcer/setup-nu@v3
        with:
          version: '0.80'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      - if: "matrix.os == 'macos-latest'"
        run: |
          nu -n -c "use action.nu *; build js aarch64-apple-darwin x86_64-apple-darwin"
      - if: "matrix.os == 'windows-latest'"
        run: |
          nu -n -c "use action.nu *; build js x86_64-pc-windows-msvc"
      - uses: actions/upload-artifact@v3
        with:
          name: ipmb-js
          path: |
            ipmb-js/*/release/ipmb_js.node
            target/*.zip
            target/*.pdb

  dist:
    needs:
      - build
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hustcer/setup-nu@v3
        with:
          version: '0.80'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: ipmb-js
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.zip
            target/*.pdb
      - run: |
          nu -n -c "use action.nu *; dist js"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
