name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-22.04, ubuntu-22.04-arm ]
    steps:
      - uses: actions/checkout@v3
      - uses: hustcer/setup-nu@v3
        with:
          version: '0.95.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      - if: "matrix.os == 'macos-latest'"
        run: |
          nu -n -c "use action.nu *; test x86_64-apple-darwin"
      - if: "matrix.os == 'windows-latest'"
        run: |
          nu -n -c "use action.nu *; test x86_64-pc-windows-msvc"
      - if: "matrix.os == 'ubuntu-22.04'"
        run: |
          nu -n -c "overlay use action.nu; test x86_64-unknown-linux-gnu"
      - if: "matrix.os == 'ubuntu-22.04-arm'"
        run: |
          nu -n -c "overlay use action.nu; test aarch64-unknown-linux-gnu"
